### ISSUE TITLE
"Sorteio" para o ganhador do LIVRO: Construindo uma Aplicação E-commerce com MEAN

### ISSUE THREAD

**Issue by suissa** [Webschool-io/Project-Marketplace-Ecommerce#3]
Quem quiser GANHAR esse livro [ 
Construindo uma Aplicação E-commerce com MEAN](http://novatec.com.br/livros/ecommerce-mean/), da Novatec, precisa **GARANTIR** que irá implementar **tudo que está no livro** e após isso refatorar para nossa arquitetura atômica, com minha ajuda é claro.

Então comente: EU QUERO

Que analisarei cada um para ver quem se adequa mais para esse projeto.

ps: **APENAS PARA ALUNOS QUE ENVIARAM EXERCÍCIOS NOS 3 MÓDULOS: MongoDB, Node.js e Angular!**

**Comment by rogerin** [comment]
EU QUERO

**Comment by aaoliveira** [comment]
0/ Eu QUERO

**Comment by phpricardo** [comment]
Eu quero! (alias rodei, pois não tenho os requisitos) boa sorte para quem ganhar. :dash:

**Comment by JrzenonDev** [comment]
EU QUERO

**Comment by natansevero** [comment]
Eu quero!

**Comment by roniewill** [comment]
I Want

**Comment by souzacristsf** [comment]
Eu quero suissa.

**Comment by hc3** [comment]
eu quero

**Comment by omariosouto** [comment]
YO

**Comment by caionorder** [comment]
EU QUERO

**Comment by ghost** [comment]
Eu Quero!

**Comment by steniowagner** [comment]
EEEEU!!!!

**Comment by guilhermefsousa** [comment]
Eu quero!!!

**Comment by jayralencar** [comment]
Eu quero.

**Comment by suissa** [comment]
**APENAS PARA ALUNOS QUE ENVIARAM EXERCÍCIOS NOS 3 MÓDULOS: MongoDB, Node.js e Angular!**

**Comment by candidosouza** [comment]
Eu Quero!!!

**Comment by cristianounix** [comment]
Quero !

**Comment by ednilsonamaral** [comment]
Putz, show de bola. E-commerce com MEAN, demorou!

**EU QUERO**

**Comment by ghost** [comment]
EU QUERO

**Comment by TL-Developer** [comment]
AAhhhhh, eu quero né rapaz ;)

**Comment by adslima** [comment]
Eu Quero muitoooooooooooo

**Comment by juniorthiesen** [comment]
sim ou claro que sim!

**Comment by rildoc** [comment]
Eu quero

**Comment by iamstarkdev** [comment]
Eu quero <3

**Comment by cassianomon** [comment]
EU QUERY.IO

**Comment by nordyc** [comment]
EU!!

**Comment by manzettidenis** [comment]
+1 
<3 quero !

**Comment by Eldius** [comment]
Também quero...

**Comment by ronibs** [comment]
EU QUERO

**Comment by ranielli** [comment]
Quero

**Comment by rogeriosblack** [comment]
Euuuu

**Comment by suissa** [comment]
Todos mandaram exercícios nos 3 módulos?

**Comment by haagweb** [comment]
Eu queroooooooo... !!! Siiimmm...!!

**Comment by FelipeDeveloperFullStack** [comment]
Eu quero

**Comment by pablozaniolo** [comment]
Eu quero!

**Comment by jamesonmiranda** [comment]
Eu quero

**Comment by suissa** [comment]
QUero saber quem vai conseguir dedicar PELO MENOS 1 hora por dia a esse projeto!

Quem realmente PUDER se dedicar bastante a esse projeto pois deve ser feito em 1 mês!

Se você ainda quiser comente abaixo:  CONCORDO.

**Comment by ednilsonamaral** [comment]
**CONCORDO!**

**Comment by rogerin** [comment]
Estou com um livro aqui, recomendo a todos, sem falar que ele alem do MEAN, ele é todo realtime.. :)

**Comment by hc3** [comment]
CONCORDO

**Comment by pablozaniolo** [comment]
CONCORDO!

**Comment by jamesonmiranda** [comment]
CONCORDO

**Comment by suissa** [comment]
OS 2 primeiros por coincidencia são um dos mais ativos no curso e foram escolhidos:
- @ednilsonamaral 
- @hc3 

Quem não foi escolhido só não ganhrá o livro nem terá admin no repositório, mas poderá criar/matar issues e enviar pull requests, blz?

**Comment by ghost** [comment]
CONCORDO (ATRASADO) POARR
